---
# tasks file for ansible-role-hosts-deploy

- name: deploy hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
  when: hostvars[item].ansible_host is defined
  with_items: groups['{{GROUP_NAME}}']
